server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # 針對 GitHub Pages base 網址的相容設定
    location /personalrecord/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
